server:
#  port: ${random.int(10000,11000)}
  port: 9099

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    throw-exception-if-no-handler-found: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:192.168.1.46}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:tiny-backend-mnt}?characterEncoding=utf8&useSSL=false
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:pass}
  web:
    resources:
      add-mappings: false

